### ISSUE TITLE
Checkstyle configuration cannot be parsed by Gradle plugin

### ISSUE THREAD

**Issue by SoerenHenning** [cau-se/code-quality-configurations#10]
It seems like the Gradle plugin does know about `${config_loc}`, which however contradicts the [official documentation](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_configuration) of the plugin. Further investigation has to be done.

Error message is (using `--stacktrace`):

````
Execution failed for task ':checkstyleMain'.
> Unable to create Root Module: config{.../checkstyle.xml}, classpath {...}
...
* Exception is:
...
Caused by: org.xml.sax.SAXException: Property ${config_loc} has not been set
````

**Comment by Alexander-Krause** [comment]
Can confirm, same error on my side.

**Comment by SoerenHenning** [comment]
Everything works fine when putting both checkstyle files in `config/checkstyle/` as in the [default configuration](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_project_layout).

**Comment by SoerenHenning** [comment]
To solve this issue, a configuration directory instead of (**or in addition to**) a configuration file has to be set. That means, if the checkstyle files are not located under `config/checkstyle`, the parameter `configDir = file("config")` has to be set, where `config` is the directory of the checkstyle files.

As this ticket is related to the to the configuration of the Gradle plugin not our checkstyle configuration itself, I am going to close it.

**Comment by Alexander-Krause** [comment]
Ok, but we should mention that in a potential README.md 'Gradle Section'.

**Comment by SoerenHenning** [comment]
Yes, I'm going to provide an exemplary/template `build.gradle` file when all tools are configured.

**Comment by Alexander-Krause** [comment]
Since my config folder is called `conf`, the Checkstyle Gradle Configuration requires the following lines to work:

```
configFile = file("PATH/TO/checkstyle.xml")
configProperties = [
  'config_loc': file('PATH/TO/FOLDER/CONTAINING/CHECKSTYLE-CONFIGURATION')
]
```
